# Generated by Django 3.0 on 2019-12-05 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_num', models.IntegerField(validators=\
                    [django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(29)])),
                ('slot_subject', models.CharField(max_length=60)),
                ('slot_type', models.CharField(max_length=32)),
                ('slot_group', models.CharField(max_length=60)),
                ('slot_subgroup', models.CharField(max_length=60)),
                ('slot_location', models.IntegerField(validators=\
                    [django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(63)])),
                ('slot_teacher', models.CharField(max_length=60)),
                ('slot_week', models.IntegerField(validators=\
                    [django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)])),
            ],
            options={
                'verbose_name_plural': 'slots',
                'ordering': ['slot_week', 'slot_num', 'slot_group', 'slot_subgroup'],
            },
        ),
    ]
